### ISSUE TITLE
Add server-side rendered pages and corresponding views for registration, email confirmation, password reset and password change.

### ISSUE THREAD

**Issue by uliSchuster** [ClairBerlin/managair#86]

**Comment by uliSchuster** [comment]
Currently, user registration, email confirmation and password reset is available via the REST API only. The problem with this solution is threefold:
- A third-party client app does get access to the user's password (instead of a short-lived token only).
- Each third-party client must implement the workflows for registration, password reset etc.
- The confirmation link in the email currently points nowhere, because there is no web view to handle the link.

**Comment by jawebada** [comment]
The Django account management templates have been activated and edited to match the website design.
